import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):
 initial=True
 dependencies=[('catalog','0001_initial'),('companies','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='License',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('license_number',models.CharField(blank=True,max_length=40,unique=True)),('status',models.CharField(choices=[('active','Aktiv'),('free','Frei'),('expired','Abgelaufen'),('blocked','Gesperrt'),('payment_review','Zahlung prüfen'),('refunded','Refundiert')],default='free',max_length=30)),('valid_from',models.DateTimeField(blank=True,null=True)),('valid_until',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='licenses',to='companies.company')),('owner_user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='owned_licenses',to=settings.AUTH_USER_MODEL)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='licenses',to='catalog.product'))],options={'indexes':[models.Index(fields=['status','valid_until'],name='licenses_l_status_idx'),models.Index(fields=['company','product'],name='licenses_l_company_idx')],'constraints':[models.CheckConstraint(condition=Q(company__isnull=False,owner_user__isnull=True)|Q(company__isnull=True,owner_user__isnull=False),name='license_exactly_one_owner_type'),models.CheckConstraint(condition=Q(valid_from__isnull=True,valid_until__isnull=True)|Q(valid_from__isnull=False,valid_until__gt=models.F('valid_from')),name='license_valid_window')]}),
  migrations.CreateModel(name='LicenseAssignment',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_at',models.DateTimeField(auto_now_add=True)),('ended_at',models.DateTimeField(blank=True,null=True)),('license',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='assignments',to='licenses.license')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='license_assignments',to=settings.AUTH_USER_MODEL))],options={'indexes':[models.Index(fields=['user','ended_at'],name='licenses_la_user_idx')],'constraints':[models.UniqueConstraint(condition=Q(ended_at__isnull=True),fields=('license',),name='one_active_assignment_per_license')]}),
  migrations.CreateModel(name='LicenseReminder',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('kind',models.CharField(choices=[('t60','T-60'),('t30','T-30'),('t0','Abgelaufen')],max_length=10)),('target_valid_until',models.DateTimeField()),('status',models.CharField(choices=[('pending','Ausstehend'),('queued','In Warteschlange'),('sent','Gesendet'),('error','Fehler')],default='pending',max_length=20)),('queued_at',models.DateTimeField(blank=True,null=True)),('sent_at',models.DateTimeField(blank=True,null=True)),('error',models.TextField(blank=True)),('license',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reminders',to='licenses.license'))],options={'constraints':[models.UniqueConstraint(fields=('license','kind','target_valid_until'),name='uniq_license_reminder_expiry')]})]
