# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_licenseassignmentlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='license',
            new_name='licenses_li_status_3263d5_idx',
            old_name='licenses_l_status_idx',
        ),
        migrations.RenameIndex(
            model_name='license',
            new_name='licenses_li_company_05ea28_idx',
            old_name='licenses_l_company_idx',
        ),
        migrations.RenameIndex(
            model_name='licenseassignment',
            new_name='licenses_li_user_id_2e29e5_idx',
            old_name='licenses_la_user_idx',
        ),
        migrations.RenameIndex(
            model_name='licenseassignmentlink',
            new_name='licenses_li_company_e23fc7_idx',
            old_name='licenses_li_company_ec3db4_idx',
        ),
        migrations.RenameIndex(
            model_name='licenseupgraderequest',
            new_name='licenses_li_company_5b5119_idx',
            old_name='licenses_up_company_4031bd_idx',
        ),
    ]
