FROM golang:1.26.6-alpine3.23 AS build

ARG CADVISOR_COMMIT=5bf5d43ac6f60d7ee36a13b4d5b4a78ad2d0abc7

RUN apk add --no-cache \
      bash build-base cmake device-mapper findutils git libc6-compat linux-headers \
      ndctl-dev pkgconfig python3 thin-provisioning-tools wget zfs \
    && git clone https://github.com/google/cadvisor.git /src \
    && cd /src \
    && git checkout "$CADVISOR_COMMIT" \
    && test "$(git rev-parse HEAD)" = "$CADVISOR_COMMIT"

WORKDIR /tmp
RUN wget -q https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz \
    && echo "112bced9a67d565ff0ce6c2bb90452516d1183e5  libpfm-4.11.0.tar.gz" | sha1sum -c - \
    && tar -xzf libpfm-4.11.0.tar.gz \
    && export DBG="-g -Wall" \
    && make -e -C libpfm-4.11.0 \
    && make install -C libpfm-4.11.0

WORKDIR /src
RUN go get golang.org/x/crypto@v0.55.0 google.golang.org/grpc@v1.83.2 \
    && go mod tidy \
    && (cd lib && go get golang.org/x/crypto@v0.55.0 google.golang.org/grpc@v1.83.2 && go mod tidy) \
    && (cd cmd && go get golang.org/x/crypto@v0.55.0 google.golang.org/grpc@v1.83.2 && go mod tidy) \
    && export GO_TAGS="libpfm,netgo" \
    && GO_CGO_ENABLED=1 GO_FLAGS="-tags=$GO_TAGS" ./build/build.sh \
    && test -x /src/_output/cadvisor

FROM ghcr.io/google/cadvisor:v0.60.6
USER root
RUN apk upgrade --no-cache
COPY --from=build /src/_output/cadvisor /usr/bin/cadvisor
RUN /usr/bin/cadvisor --version
