import uuid
from django.db import migrations, models
from django.db.models import Q
class Migration(migrations.Migration):
 initial=True; dependencies=[]
 operations=[
  migrations.CreateModel(name='SystemAlert',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('code',models.CharField(max_length=100)),('severity',models.CharField(choices=[('warning','Warnung'),('critical','Kritisch')],max_length=20)),('message',models.CharField(max_length=500)),('active',models.BooleanField(default=True)),('resolved_at',models.DateTimeField(blank=True,null=True))],options={'indexes':[models.Index(fields=['active','severity','created_at'],name='ops_alert_state_idx')],'constraints':[models.UniqueConstraint(condition=Q(active=True),fields=('code',),name='uniq_active_system_alert')]}),
  migrations.CreateModel(name='BackupRecord',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('status',models.CharField(max_length=30)),('provider_ref',models.CharField(blank=True,max_length=200)),('size_bytes',models.BigIntegerField(default=0)),('finished_at',models.DateTimeField(blank=True,null=True))],options={'ordering':['-finished_at','-created_at']}),
  migrations.CreateModel(name='RestoreTest',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('status',models.CharField(max_length=30)),('backup_ref',models.CharField(max_length=200)),('started_at',models.DateTimeField()),('finished_at',models.DateTimeField(blank=True,null=True)),('details',models.JSONField(default=dict))],options={'ordering':['-started_at']}),
  migrations.CreateModel(name='WorkerHeartbeat',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(default='default',max_length=80,unique=True)),('last_seen_at',models.DateTimeField()),('hostname',models.CharField(blank=True,max_length=200))]),
  migrations.CreateModel(name='TaskFailure',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('task_id',models.CharField(max_length=100,unique=True)),('task_name',models.CharField(max_length=200)),('error',models.CharField(max_length=1000)),('failed_at',models.DateTimeField()),('resolved_at',models.DateTimeField(blank=True,null=True))],options={'ordering':['-failed_at'],'indexes':[models.Index(fields=['resolved_at','failed_at'],name='ops_taskfail_state_idx')]})]
