# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_beatheartbeat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='ops_systema_active_99d084_idx',
            old_name='ops_alert_state_idx',
        ),
        migrations.RenameIndex(
            model_name='taskfailure',
            new_name='ops_taskfai_resolve_e3ea6f_idx',
            old_name='ops_taskfail_state_idx',
        ),
    ]
