import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):
 initial=True
 dependencies=[('catalog','0001_initial'),('companies','0001_initial'),('licenses','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='Order',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('order_number',models.CharField(max_length=40,unique=True)),('status',models.CharField(choices=[('draft','Entwurf'),('payment_open','Zahlung offen'),('paid','Bezahlt'),('failed','Fehlgeschlagen'),('canceled','Storniert')],default='draft',max_length=30)),('currency',models.CharField(default='EUR',max_length=3)),('gross_total',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('tax_total',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('billing_snapshot',models.JSONField(default=dict)),('idempotency_key',models.CharField(max_length=80,unique=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='companies.company')),('private_user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='private_orders',to=settings.AUTH_USER_MODEL))],options={'indexes':[models.Index(fields=['status','created_at'],name='orders_o_status_idx')],'constraints':[models.CheckConstraint(condition=Q(company__isnull=False,private_user__isnull=True)|Q(company__isnull=True,private_user__isnull=False),name='order_exactly_one_customer'),models.CheckConstraint(condition=Q(gross_total__gte=0),name='order_gross_nonnegative'),models.CheckConstraint(condition=Q(tax_total__gte=0),name='order_tax_nonnegative')]}),
  migrations.CreateModel(name='OrderItem',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('quantity',models.PositiveIntegerField(default=1)),('unit_gross',models.DecimalField(decimal_places=2,max_digits=10)),('unit_net',models.DecimalField(decimal_places=2,max_digits=10)),('tax_rate',models.DecimalField(decimal_places=2,max_digits=5)),('product_name_snapshot',models.CharField(max_length=160)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='orders.order')),('price_version',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='catalog.productprice')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='catalog.product')),('target_license',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='renewal_order_items',to='licenses.license'))],options={'constraints':[models.CheckConstraint(condition=Q(quantity__gt=0),name='order_item_quantity_positive'),models.CheckConstraint(condition=Q(unit_gross__gte=0),name='order_item_gross_nonnegative'),models.CheckConstraint(condition=Q(unit_net__gte=0),name='order_item_net_nonnegative')]})]
