# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_a_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_object__0e78a5_idx',
            old_name='audit_a_object_idx',
        ),
    ]
