# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenthub', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faqentry',
            new_name='contenthub__audienc_bc5020_idx',
            old_name='contenthub_f_audienc_46b102_idx',
        ),
    ]
