import uuid
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):
 initial=True; dependencies=[]
 operations=[
  migrations.CreateModel(name='Product',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('code',models.CharField(max_length=60,unique=True)),('name',models.CharField(max_length=160)),('description',models.TextField(blank=True)),('active',models.BooleanField(default=True)),('visible',models.BooleanField(default=True)),('purchasable',models.BooleanField(default=True)),('default_license_days',models.PositiveIntegerField(default=365)),('default_device_limit',models.PositiveSmallIntegerField(default=2)),('reminder_1_days',models.PositiveSmallIntegerField(default=60)),('reminder_2_days',models.PositiveSmallIntegerField(default=30)),('critical_warning_days',models.PositiveSmallIntegerField(default=7))],options={'constraints':[models.CheckConstraint(condition=Q(default_license_days__gt=models.F('reminder_1_days'))&Q(reminder_1_days__gt=models.F('reminder_2_days'))&Q(reminder_2_days__gt=models.F('critical_warning_days'))&Q(critical_warning_days__gt=0)&Q(default_device_limit__gt=0),name='product_reminder_order_valid')]}),
  migrations.CreateModel(name='Feature',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('code',models.CharField(max_length=100,unique=True)),('name',models.CharField(max_length=160))]),
  migrations.CreateModel(name='TaxRule',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('country',models.CharField(max_length=2)),('customer_type',models.CharField(choices=[('company','Firma'),('private','Privat')],max_length=20)),('tax_rate',models.DecimalField(decimal_places=2,default=19,max_digits=5)),('require_vat_id',models.BooleanField(default=False)),('require_tax_number',models.BooleanField(default=False)),('active',models.BooleanField(default=True))],options={'constraints':[models.UniqueConstraint(condition=Q(active=True),fields=('country','customer_type'),name='uniq_active_tax_rule'),models.CheckConstraint(condition=Q(tax_rate__gte=0)&Q(tax_rate__lte=100),name='tax_rate_valid_percent')]}),
  migrations.CreateModel(name='ProductPrice',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('price_type',models.CharField(choices=[('new','Neukauf'),('renewal','Verlängerung')],max_length=20)),('gross_amount',models.DecimalField(decimal_places=2,max_digits=10)),('currency',models.CharField(default='EUR',max_length=3)),('valid_from',models.DateTimeField()),('valid_until',models.DateTimeField(blank=True,null=True)),('active',models.BooleanField(default=True)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='prices',to='catalog.product'))],options={'indexes':[models.Index(fields=['product','price_type','valid_from'],name='catalog_pp_stream_idx')],'constraints':[models.CheckConstraint(condition=Q(gross_amount__gte=0),name='product_price_nonnegative'),models.CheckConstraint(condition=Q(valid_until__isnull=True)|Q(valid_until__gt=models.F('valid_from')),name='product_price_valid_window')]}),
  migrations.CreateModel(name='ProductEntitlement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('enabled',models.BooleanField(default=True)),('feature',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='catalog.feature')),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='entitlements',to='catalog.product'))],options={'constraints':[models.UniqueConstraint(fields=('product','feature'),name='uniq_product_feature')]})]
