# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productprice',
            new_name='catalog_pro_product_2e5f65_idx',
            old_name='catalog_pp_stream_idx',
        ),
    ]
