# Generated by Django 5.2.17 on 2026-09-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_totp_step',
            field=models.BigIntegerField(default=-1),
        ),
    ]
