# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceregistration',
            new_name='devices_dev_user_id_40cac7_idx',
            old_name='devices_d_user_idx',
        ),
    ]
