import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Company', fields=[
        ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),
        ('customer_number',models.CharField(max_length=30,unique=True)),('name',models.CharField(max_length=200)),('legal_form',models.CharField(blank=True,max_length=80)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=60)),('street',models.CharField(blank=True,max_length=160)),('house_number',models.CharField(blank=True,max_length=40)),('postal_code',models.CharField(blank=True,max_length=20)),('city',models.CharField(blank=True,max_length=120)),('country',models.CharField(default='DE',max_length=2)),('vat_id',models.CharField(blank=True,max_length=40)),('tax_number',models.CharField(blank=True,max_length=60)),('status',models.CharField(choices=[('active','Aktiv'),('inactive','Inaktiv')],default='active',max_length=20))],
        options={'indexes':[models.Index(fields=['name'],name='companies_c_name_idx'),models.Index(fields=['status','country'],name='companies_c_status_idx')]}),
      migrations.CreateModel(name='PrivateCustomerProfile',fields=[
        ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('customer_number',models.CharField(max_length=30,unique=True)),('street',models.CharField(blank=True,max_length=160)),('house_number',models.CharField(blank=True,max_length=40)),('postal_code',models.CharField(blank=True,max_length=20)),('city',models.CharField(blank=True,max_length=120)),('country',models.CharField(default='DE',max_length=2)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='private_customer',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='Membership',fields=[
        ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('role',models.CharField(choices=[('admin','Firmenadministrator'),('member','Mitarbeiter')],default='member',max_length=20)),('active',models.BooleanField(default=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='memberships',to='companies.company')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='company_memberships',to=settings.AUTH_USER_MODEL))],
        options={'indexes':[models.Index(fields=['company','active','role'],name='companies_m_company_idx')],'constraints':[models.UniqueConstraint(condition=Q(active=True),fields=('company','user'),name='uniq_active_company_user'),models.UniqueConstraint(condition=Q(active=True,role='admin'),fields=('company',),name='uniq_active_company_admin'),models.UniqueConstraint(condition=Q(active=True),fields=('user',),name='uniq_active_company_membership_per_user')]}),
      migrations.CreateModel(name='Invitation',fields=[
        ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('email',models.EmailField(max_length=254)),('first_name',models.CharField(blank=True,max_length=120)),('last_name',models.CharField(blank=True,max_length=120)),('token_hash',models.CharField(max_length=64,unique=True)),('expires_at',models.DateTimeField()),('accepted_at',models.DateTimeField(blank=True,null=True)),('revoked_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='invitations',to='companies.company')),('invited_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='sent_invitations',to=settings.AUTH_USER_MODEL))],
        options={'indexes':[models.Index(fields=['company','email','expires_at'],name='companies_i_company_idx')],'constraints':[models.UniqueConstraint(condition=Q(accepted_at__isnull=True,revoked_at__isnull=True),fields=('company','email'),name='uniq_open_company_invite')]})]
