# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='companies_c_name_2d8260_idx',
            old_name='companies_c_name_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='companies_c_status_783b46_idx',
            old_name='companies_c_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='companies_i_company_eeb8aa_idx',
            old_name='companies_i_company_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='companies_m_company_e1ce09_idx',
            old_name='companies_m_company_idx',
        ),
    ]
