import {readFile,writeFile} from 'node:fs/promises';
const logo='<a class="brand" href="/" aria-label="PromptMaster Startseite"><span class="logo-crop" aria-hidden="true"></span><span class="sr-only">PromptMaster</span></a>';
const freeIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="19" fill="none" stroke="currentColor" stroke-width="1.5" stroke-dasharray="17 4"/><path d="M11 24h9m-4.5-4.5v9m10-4.5h9m-4.5-4.5v9" stroke="currentColor" stroke-width="1.6"/></svg>';
const proIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="m7 15 10 8 7-15 7 15 10-8-6 21H13Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M13 42h22" stroke="currentColor" stroke-width="3"/></svg>';
await writeFile('index.html',`<!doctype html>
<html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#030b1b"><title>PromptMaster by netstyle – Bessere Prompts für Microsoft Copilot</title><meta name="description" content="Vom Anliegen zum präzisen Copilot-Prompt. PromptMaster Free und Pro. Pro: 2,99 € inklusive MwSt. pro Benutzer und Monat bei jährlicher Abrechnung."><link rel="stylesheet" href="/src/style.css"><link rel="stylesheet" href="/src/immersive.css"></head>
<body><a class="skip" href="#main">Zum Inhalt</a>
<div class="scene-world" aria-hidden="true"><div class="landscape"></div><div class="scene-aura"></div><div class="head-stage"><canvas id="particle-head"></canvas><div class="head-fallback" hidden>Aus deiner Aufgabe wird ein präziser Copilot-Prompt.</div></div><div class="scene-shade"></div></div>
<header>${logo}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menü <span>☰</span></button><nav id="navigation" aria-label="Hauptnavigation"><a href="/#start">Produkte</a><a href="/#funktionen">Funktionen</a><a href="/#preise">Preise</a><a href="/#vergleich">Free vs. Pro</a><a href="/#faq">FAQ</a><a href="/login/" class="login-link">Anmelden</a><a href="/free/" class="button nav-cta">Jetzt starten</a></nav></header>
<main id="main"><section class="hero" id="start"><div class="hero-grid">
<article class="product free" data-edition="free"><div class="product-heading">${freeIcon}<div><span class="edition">PROMPTMASTER</span><strong>FREE</strong></div></div><h2>Einfach starten.<br>Kostenlos nutzen.</h2><ul class="hero-features"><li>6 Microsoft-Anwendungen</li><li>Basisaufgaben je Anwendung</li><li>Grundlegende Zielgruppen</li><li>Prompt direkt kopieren</li><li>Dauerhaft kostenlos</li></ul><div class="card-bottom"><div class="price free-price">0,00 €</div><p class="price-detail">Kostenlos. Direkt im Browser.</p><a class="button secondary" href="/free/">Kostenlos starten <span>→</span></a><a class="text-link" href="#funktionen">Alle Features ansehen</a></div></article>
<div class="hero-center"><div class="hero-title"><p class="core-sentence">Aus deiner Aufgabe wird ein<br>präziser Copilot-Prompt.</p><h1>Bessere Prompts. Bessere Ergebnisse<br>mit Microsoft Copilot.</h1><a href="#funktionen" class="scroll-link"><span>↓</span> PromptMaster entdecken</a></div></div>
<article class="product pro" data-edition="pro"><div class="product-heading">${proIcon}<div><span class="edition">PROMPTMASTER</span><strong>PRO</strong></div></div><h2>Mehr Möglichkeiten.<br>Mehr Präzision.</h2><ul class="hero-features"><li>Alle Free-Funktionen</li><li>10 weitere Anwendungen</li><li>Erweiterte Analysefunktionen</li><li>Professionelle Ausgabeformate</li><li>App-spezifische Business-Prompts</li></ul><div class="card-bottom"><div class="price">2,99 €<span>/ Monat</span></div><p class="price-detail">pro Benutzer · inkl. MwSt.<br>35,88 € / Jahr · jährliche Abrechnung</p><a class="button" href="/checkout/?quantity=1">Jetzt Pro wählen <span>→</span></a><a class="text-link" href="#vergleich">Features vergleichen</a></div></article>
</div><div class="hero-properties"><span>✧ Für Microsoft Copilot entwickelt</span><span>◇ Regel- und bausteinbasiert</span><span>▧ Prompt-Erstellung im Browser</span><span>↗ Sofort einsetzbar</span></div></section><div id="content"></div></main><footer id="footer"></footer><script type="module" src="/src/main.js"></script></body></html>`);
let content=await readFile('src/content.js','utf8');
content=content.replace('Pro Benutzer / Monat, netto','Pro Benutzer / Monat, inkl. MwSt.').replace('Pro Benutzer / Jahr, netto','Pro Benutzer / Jahr, inkl. MwSt.').replace('Gesamt / Jahr, netto','Darin enthalten, netto').replace('MwSt. <span','Enthaltene MwSt. <span').replace('Gesamt / Jahr</dt>','Gesamt / Jahr, inkl. MwSt.</dt>').replace('Preise für Unternehmen in Deutschland.','Alle Preise inklusive MwSt.');
content=content.replace('<a class="brand" href="/">PROMPTMASTER<small>by netstyle</small></a>',logo);
await writeFile('src/content.js',content);
const faq=JSON.parse(await readFile('src/faq.json','utf8'));
faq.find(f=>f.question==='Was kostet PromptMaster Pro?').answer='PromptMaster Pro kostet 2,99 € inklusive MwSt. pro Benutzer und Monat bei zwölf Monaten Laufzeit.\nDie Abrechnung erfolgt jährlich im Voraus: 35,88 € inklusive MwSt. pro Benutzer und Jahr.';
await writeFile('src/faq.json',JSON.stringify(faq,null,2));
