import uuid
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 initial=True; dependencies=[('licenses','0002_licenseterm'),('orders','0001_initial')]
 operations=[
  migrations.CreateModel(name='Payment',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('provider',models.CharField(default='mollie',max_length=30)),('provider_payment_id',models.CharField(max_length=100,unique=True)),('status',models.CharField(max_length=40)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('currency',models.CharField(default='EUR',max_length=3)),('method',models.CharField(blank=True,max_length=50)),('paid_at',models.DateTimeField(blank=True,null=True)),('processed_paid',models.BooleanField(default=False)),('last_provider_payload',models.JSONField(default=dict)),('order',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payments',to='orders.order'))]),
  migrations.CreateModel(name='MollieEvent',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('provider_status',models.CharField(max_length=40)),('event_key',models.CharField(max_length=180,unique=True)),('processed_at',models.DateTimeField(blank=True,null=True)),('error',models.TextField(blank=True)),('retry_count',models.PositiveIntegerField(default=0)),('payment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='events',to='payments.payment'))]),
  migrations.CreateModel(name='Refund',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('provider_refund_id',models.CharField(blank=True,max_length=100,null=True,unique=True)),('amount',models.DecimalField(decimal_places=2,max_digits=10)),('remaining_days',models.PositiveIntegerField()),('status',models.CharField(choices=[('created','Erstellt'),('submitted','Übermittelt'),('succeeded','Erfolgreich'),('failed','Fehlgeschlagen')],default='created',max_length=30)),('reason',models.TextField(blank=True)),('payment',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='refunds',to='payments.payment')),('term',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='refund',to='licenses.licenseterm'))])]
