import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
class Migration(migrations.Migration):
 initial=True; dependencies=[('orders','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='LegalDocument',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('doc_type',models.CharField(choices=[('terms','AGB'),('privacy','Datenschutz'),('withdrawal','Widerruf'),('license','Lizenzbedingungen')],max_length=30)),('version',models.CharField(max_length=30)),('content',models.TextField()),('valid_from',models.DateTimeField()),('active',models.BooleanField(default=True))],options={'constraints':[models.UniqueConstraint(fields=('doc_type','version'),name='uniq_legal_version'),models.UniqueConstraint(condition=Q(active=True),fields=('doc_type',),name='uniq_active_legal_type')]}),
  migrations.CreateModel(name='RetentionPolicy',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('data_class',models.CharField(max_length=80,unique=True)),('retain_days',models.PositiveIntegerField()),('active',models.BooleanField(default=True))]),
  migrations.CreateModel(name='DeletionRequest',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('requested_at',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('open','Offen'),('processing','In Bearbeitung'),('completed','Abgeschlossen'),('rejected','Abgelehnt')],default='open',max_length=30)),('completed_at',models.DateTimeField(blank=True,null=True)),('notes',models.TextField(blank=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='LegalAcceptance',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('accepted_at',models.DateTimeField(auto_now_add=True)),('evidence',models.JSONField(default=dict)),('document',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='legal.legaldocument')),('order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='orders.order')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))],options={'constraints':[models.UniqueConstraint(fields=('user','document','order'),name='uniq_legal_acceptance'),models.UniqueConstraint(condition=Q(order__isnull=True),fields=('user','document'),name='uniq_account_legal_acceptance')]})]
