# Generated by Django 5.2.17 on 2026-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_studio_quality'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promptdefinition',
            new_name='prompts_pro_applica_997686_idx',
            old_name='prompts_pro_applica_e75f93_idx',
        ),
        migrations.RenameIndex(
            model_name='promptqualitysnapshot',
            new_name='prompts_pro_status_0b735e_idx',
            old_name='prompts_qua_status_245fad_idx',
        ),
        migrations.RenameIndex(
            model_name='promptqualitysnapshot',
            new_name='prompts_pro_definit_51fc31_idx',
            old_name='prompts_qua_definit_562fcc_idx',
        ),
        migrations.RenameIndex(
            model_name='promptrating',
            new_name='prompts_pro_definit_cc3355_idx',
            old_name='prompts_rat_definit_55e584_idx',
        ),
        migrations.RenameIndex(
            model_name='promptrating',
            new_name='prompts_pro_version_ebb7b0_idx',
            old_name='prompts_rat_version_d27fb4_idx',
        ),
    ]
